### ISSUE TITLE
Crash on get axon/dendrite orientation button press

### ISSUE THREAD

**Issue by flowernert** [fedebarabas/ringfinder#2]
**platform** : Windows 10 pro x64
**python** version : anaconda 3.6.4 x64
**product** : ringFinderDeveloper

I encounter a crash of your software when I press the axon/dendrite orientation button and the selected zone on the image leads to no lines/angle detected.

Error message : 

> > No lines detected with Hough line algorithm
> Traceback (most recent call last):
>   File "C:\Users\NeuroCyto\Users\Florian\gollum\ringfinder\ringfinder\ringFinderDeveloper.py", line 596, in getDirection
>     minLen, True)
>   File "C:\Users\NeuroCyto\Users\Florian\gollum\ringfinder\ringfinder\tools.py", line 203, in getDirection
>     print(text.format(th0, sigmaTh, len(lines)))
> TypeError: unsupported format string passed to NoneType.__format__

I looked at the source and understood the issue. 
In the file `tools.py`
When no lines and angles are found, the `linesFromBinary `function at line 200 returns None values for `th0 `and `sigmaTh `variables.
Then at line 203 you try to format these None value variables to floats, which is why the crash happens.

A possible way to correct it would be to build your format string depending on th0 and sigmaTh being None or not.

**Comment by fedebarabas** [comment]
Hi Florian! Thank you for the detailed report, it sounds like the fix you suggested would do the trick. Unfortunately I am not developing this any longer. I suggest posting this in this fork: https://github.com/lumasullo/Gollum or directly making a pull request there.

Thanks again!
